version: '2'
services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./misc/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'
    container_name: prometheus
  imap_exporter:
    build:
      context: .
      dockerfile: ./misc/Dockerfile
    ports:
      - '9993:9993'
    container_name: imap_exporter
  grafana:
    image: grafana/grafana
    ports:
      - '3000:3000'
    container_name: grafana
